apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-tenant/partner-catalog/partner-catalog@sha256:44cad0ab170bb20f40d7fd5c385e1837bad334f774bbb9704259470ff201ff1a
        name: my-java-springboot
        resources: {}
status: {}
