apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-tenant/partner-catalog/partner-catalog@sha256:c18a7f154cf47635ae871621433972fb2bd364a0789bc631837ce98d2f0e7a54
        name: my-java-springboot
        resources: {}
status: {}
